chore: add types for TileLoadingMonitor
Greenstand/treetracker-web-map-core pull request #136
Opened 2022-11-15 07:39 UTC by ojafero

2022-11-15 13:51 UTC, RubenSmn commented on src/types.ts
> +import TileLoadingMonitor from './TileLoadingMonitor'
I don't think this belongs here :sweat_smile:

2022-11-15 13:52 UTC, RubenSmn requested changes

2022-11-15 13:52 UTC, RubenSmn commented on src/types.ts
> +import TileLoadingMonitor from './TileLoadingMonitor'
I think was a miss import :sweat_smile:

2022-11-16 08:10 UTC, RubenSmn approved these changes

2022-11-16 08:10 UTC, merged

2022-11-17 02:06 UTC, dadiorchen commented on src/types.ts
> + }
Do you think put the dedicate type for some object into the object's file is better? In my view, it is more concentrated.